---
                                                    # first cleanup with bash ~/px/scripts/full-setup.sh
- name: Generate JMart Survey Results               # Generate reports based on raw csv survey results
  hosts: planetexpress:!farnsworth:!zoidberg        # collected (via other means) from JMart customers
  connection: ssh
  gather_facts: yes

  vars:
     surveycsv: ~/mycode/surveyresults.csv
     shipping_reporter: bender                      # host assigned to generate shipping reports
     gas_reporter: fry                              # host assigned to generate gas reports

  vars_files:                                       # Obtain the survey results, mysteriously written
     - ~/mycode/surveyresults.yml                   # here via unknown means

  vars_prompt:
     - name: "reporttype"
       private: no
       prompt: "What JMart client satisfaction report would you like to generate? (shipping, gas, both) "

  tasks:
    - name: Check reporttype
      debug:
        msg: "{{ reporttype }}"

          #    - name: Install figlet                # install figlet for report headers
          #      ansible.builtin.apt:
          #        name: figlet
          #        state: present
          #      become: yes                         # elevate to admin

    - name: Distribute survey results     # send the csv survey results (gathered via other means) to the required hosts
      ansible.builtin.copy:
        src: "{{ surveycsv }}"            # source, on the controller
        dest: ~/                          # destination, on the host
        backup: yes                       # backup original dest file
        force: yes                        # if dest exists, copy anyways if different

    - name: Generate gas survey reports       # assigned hosts generate their report and return it
      #      debug:
      #        msg: "Gas Report"
      
      ansible.builtin.debug:
        var: "{{ item }}"
        loop: "{{ survey_results|dict2items }}"

      when: (inventory_hostname == gas_reporter) and (reporttype == "gas" or reporttype == "both")

    - name: Generate gas survey reports       # assigned hosts generate their report and return it
      debug:
        msg: "Shipping Report"
      when: (inventory_hostname == shipping_reporter) and (reporttype == "shipping" or reporttype == "both")



          #    - name: Display survey reports        # display the reports


          #    - name: Get survey reports            # controller gets the survey reports from the hosts

